### PR TITLE
fixed an issue with Sound sensor

### PR DESCRIPTION
**Pull request by CleoQc**
Forum thread for reference http://www.dexterindustries.com/topic/audio-sensor-problems/

### CODE REVIEW

**Comment by DexterInd** [comment]
Question, I'm only seeing the variable "sound_len" one time.

**Comment by CleoQc** [comment]
Same for me. I question its pertinence

**Comment by DexterInd** [comment]
@karan259 can you weigh in on this?  Something broken here?

**Comment by karan259** [comment]
@DexterInd @CleoQc : I think that variable might be a remnant of something in the older version of how we measure the analog read. I think we should remove **sound_len, window_size and t** and change line 313 https://github.com/CleoQc/GoPiGo/blob/60a24536cfaa8e762fd92ef98393304699b0fa59/Software/Scratch/GoPiGoScratch.py#L313 to just `avg = peak/50`. 

Does that sound good.

**Comment by DexterInd** [comment]
Sounds good to me.  I vote yes.

**Comment by CleoQc** [comment]
Great! I was tempted to do that but went with the safest approach. Cleaner to remove those lines!

**Comment by CleoQc** [comment]
Ready to pull in.

**Pull request merged**
