### PR TITLE
Robert lucian hotfix/software/python/ir server not working

### PR DESCRIPTION
**Pull request by DexterInd**

### CODE REVIEW

**Comment by DexterInd** [comment]
@RobertLucian  For some reason the example `lirc_example.py` does not work after this is merged.  Here's the error:

```
pi@dex:~/Dexter/GoPiGo/Software/Python/ir_remote_control/examples $ sudo python lirc_example.py
Traceback (most recent call last):
  File "lirc_example.py", line 40, in <module>
    sockid = lirc.init("keyes", blocking = False)
  File "lirc.pyx", line 122, in lirc.init (lirc/lirc.c:1755)
lirc.InitError: Unable to initialise lirc (socket was -1 from C library).
```

**Comment by DexterInd** [comment]
The good news is that Scratch still works though!

**Comment by RobertLucian** [comment]
@DexterInd can you try out `ir_recv_example.py` instead? 
That's the one I've been using.

**Comment by DexterInd** [comment]
Yes, ir_recv_example.py works just fine.

**Comment by RobertLucian** [comment]
Well, then I'll make a new PR that removes the `lirc_example.py` file.
Type the following command in the terminal:

- `sudo systemctl stop ir-server.service`
- `sudo python lirc_example.py`

It should work. Only one instance is allowed at a time.
But I haven't tried this out - the `lirc_example.py` wasn't my target here.

**Comment by DexterInd** [comment]
Have you tried these commands?

**Pull request merged**
