### PR TITLE
from __future__ added

### PR DESCRIPTION
**Pull request by CleoQc**
force print statements and integer divisions to behave like Python3 at all times

### CODE REVIEW

**Comment by CleoQc** [comment]
@karan259 Could you double check the read_status one?

**Comment by CleoQc** [comment]
Comments added

**Comment by karan259** [comment]
@DexterInd : looks good to merge. Shoban has tested the major programs and no big problems

**Comment by DexterInd** [comment]
Thank you @CleoQc and @karan259 and @Shoban94 !

**Pull request merged**
