### PR TITLE
Document several python gopigo functions

### PR DESCRIPTION
**Pull request by ExcaliburZero**
Add documentation for a few of the functions in the Python gopigo library.

I've yet to test out the updated file on a GoPiGo2, but I'll do this sometime in the next few days. Since this just makes changes to the documentation it shouldn't effect the functionality, but I'll try it out just to make sure.

Let me know if there are any changes you would like me to make to the added documentation.

### CODE REVIEW

**Comment by CleoQc** [comment]
@RobertLucian  Can you take a look at the documentation ?

**Comment by RobertLucian** [comment]
@ExcaliburZero the documentation is good as it is. Do you intent on adding more documentation on this PR or is it okay to merge this one?

**Comment by ExcaliburZero** [comment]
You can merge this PR.

I may add some more documentation later, but I'll do it in a different PR.

**Comment by RobertLucian** [comment]
Okay fantastic! Thank you @ExcaliburZero .

**Pull request merged**
