### PR TITLE
Change of spacing between the buttons

### PR DESCRIPTION
**Pull request by Shoban94**
Changed the Window frame size and the spacing of the buttons.

The problem was this window had the buttons overlapping the text when viewed on a full screen like the monitor, So I have changed the window size, the x-axis of the buttons to change the spacing between them and also their Y axis to not to overlap over the Instructions.

### CODE REVIEW

**Comment by DexterInd** [comment]
Thanks @Shoban94 !  @CleoQc can you take a look at this and approve?

**Comment by DexterInd** [comment]
Still want to make sure that @CleoQc is ok with this before we merge.

**Comment by karan259** [comment]
@DexterInd : looks good to merge.

**Comment by DexterInd** [comment]
Thanks!

**Pull request merged**
